### PR TITLE
add sass-module-importer for node-path resolution of imports

### LINKED ISSUE #37: Import from npm install files
I would like to be able to import from other projects in node_modules at runtime, using my npm path. The problem is when I have a module installed alongside other modules that are it's dependencies (as with modern version of npm) and so I can't count on the structure of node_modules.

It would turn things like this:

```scss
@import "../../../node_modules/material-colors/dist/colors.scss";
```

which breaks if the module is installed alongside material-colors. The path that would work in that case, but not standalone, would look like this:

```scss
@import "../../../../material-colors/dist/colors.scss";
```

If there was even a way to count on the node_modules dir in a variable, and I could do something like this, it would work ok, even if not ideal:

```scss
@import $module_path + "material-colors/dist/colors.scss";
```

I'd prefer to be able to do something like this:

```scss
@import "material-colors/dist/colors.scss";
```
less/lessify works this way.

[This module](https://www.npmjs.com/package/sass-module-importer) gets close, but has requirements to setup package.json with the right structure. I made [an issue](https://github.com/lucasmotta/sass-module-importer/issues/17) that tracks that, so maybe it will be as simple as adding that module to the node-sass options.

### PR DESCRIPTION
**Pull request by konsumer**
resolves #37

### CODE REVIEW

**Comment by konsumer** [comment]
Hmm. upon further testing, I get this:
```
TypeError: Path must be a string. Received [Function]
```

Maybe I need a newer version of node-sass?

**Comment by konsumer** [comment]
(my issue is resolved with later commits and this is ready to go!)

**Comment by davidguttman** [comment]
Looks like Travis has an issue, but only on Node v0.10... I guess that's fine.

**Comment by konsumer** [comment]
Yeh, I looked at it, and couldn't find anything I did that would trigger that. Thanks!

**Comment by davidguttman** [comment]
In `2.0.0`

**Comment by konsumer** [comment]
sweet! thanks.

**Pull request merged**
