### PR TITLE
Bump to node-sass 2.0.1 stable

### PR DESCRIPTION
**Pull request by oncletom**

### CODE REVIEW

**Comment by call-a3** [comment]
I'll look into this. Either way multiple dependencies are in need of an update, so I'll look into that. I will also consider this an answer to your comment on #17.

**Comment by call-a3** [comment]
@davidguttman I've prepared a branch (including this pull request) with updated dependencies. However, I'm not sure what version to use as the "new version". I think (assuming we're using semver 2.0) it should be 0.7.0 (since the updated dependencies could be considered an added feature), but maybe you prefer another number? 

I've pushed the branch (using git flow) to a develop branch. I'll prepare a new release when I have confirmation on the version number.

**Comment by davidguttman** [comment]
Yep, I agree with 0.7.0. Unless it's a bugfix, usually a minor bump is in order.

**Comment by call-a3** [comment]
Great! Then all that needs to be done is publish the new v0.7.0 tag to npm :) (Incidently this can also be done automatically through travis, if you're interested in that ;) It's pretty easy, just adjust the .travis.yml file. Here's an example for another project of mine: [browserify-notify](https://github.com/call-a3/browserify-notify/blob/master/.travis.yml) Obviously you would need to adjust te credentials to match your own account, but that's all there is to it)

**Comment by davidguttman** [comment]
done!

**Comment by oncletom** [comment]
Thanks both of you :-)

**Pull request merged**
